project_id = "uijhwhckkwpgfjvodxfm"

[functions.generate-daily-summary]
verify_jwt = true

[functions.admin-query]
verify_jwt = true

[functions.predictive-analytics]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.get-users]
verify_jwt = true

[functions.update-user]
verify_jwt = true
